spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    main:
        web-application-type: none
    data:
        mongodb:
            database: Users
            uri: mongodb+srv://tester:testerpw@customers.4lge2rv.mongodb.net/?retryWrites=true&w=majority